spring:
  application:
    name: dodotalk-backend
    admin:
      enabled: true

  jackson:
    time-zone: Asia/Seoul

  data:
    redis:
      host: "redis-14447.c340.ap-northeast-2-1.ec2.cloud.redislabs.com"
      password: ${REDIS_PASSWORD}
      username: "default"
      port: 14447
      connect-timeout: 5000ms
      timeout: 2000ms

  datasource:
    url: jdbc:postgresql://aws-1-ap-northeast-2.pooler.supabase.com:5432/postgres
    username: postgres.pykgjzoltroojlpnhpwi
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 20_000
      idle-timeout: 300_000
      max-lifetime: 12_000_000
      validation-timeout: 5_000
      pool-name: SpringBootHikariCP
      data-source-properties:
        prepareThreshold: 5
        prepareStatementCachedQueries: 256
        prepareStatementCachedSizeMiB: 5

        tcpKeepAlive: true
        socketTimeout: 30
        connectTimeout: 10
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: true
        jdbc:
          time_zone: Asia/Seoul

jwt:
  secret: ${JWT_SECRET_BASE64}
  expiration-minutes: 15

dodotalk:
  email:
    verification:
      expiry-hours: 1
    reset-password:
      expiry-minutes: 30
  scheduling:
    time-zone: Asia/Seoul