spring:
  jpa:
    hibernate:
      ddl-auto: update

jwt:
  expiration-minutes: 30

nginx:
  require-proxy: false

dodotalk:
  rate-limit:
    ip:
      apply-limit: true
  web-socket:
    allowed-origins:
      - "${SERVER_DEFAULT_URL}"
      - "http://localhost:8080"