spring:
  jpa:
    hibernate:
      ddl-auto: update

jwt:
  expiration-minutes: 30

nginx:
  require-proxy: false

dodotalk:
  email:
    url: "http://localhost:8080"
  rate-limit:
    ip:
      apply-limit: false