spring:
  jpa:
    hibernate:
      ddl-auto: validate

jwt:
  expiration-minutes: 15

nginx:
  require-proxy: true

dodotalk:
  email:
    url: ${SERVER_DEFAULT_URL}
  rate-limit:
    ip:
      apply-limit: true